### ISSUE TITLE
Rework textures

### ISSUE THREAD

**Issue by phaazon** [phaazon/luminance-rs#199]
# Motivation

An issue (#189) showed that nvidia is being very lenient on what it’s doing with texture formats. We had several choices:

  - Drop support for RGB textures. This is a pity to me.
  - Find a mitigation. Plot twist: I haven’t found any yet.
  - Since it’s generating a segfault, we could query the actual internal format and emit errors if it’s incorrect. Problem: that feature is not compatible for GL ≤ 4.1 IIRC (or extension but fuck extensions).

# Roadmap

A set of actions must be taken.

- [x] #200 Implement texture’s size check. That check is needed to ensure we are not going to upload texels to the GPU for `N` bytes via an opaque pointer while we tell it to read `M` with `M ≥ N` bytes. That would generate segfault and overflows.
- [x] #201 Remove RGB texture format support. It’s a pity but I don’t want to risk segfaults on clients’ ends.
- [x] #202 Rework pixel format code so that we can also support `SNORM`.

**Comment by phaazon** [comment]
Closing as everything got fixed. The problem was due to unpacking alignment and not RGB textures. Should be fine on nvidia now.
